import type { PbiProject } from "./pbiClient";

// Em modo dev (sem PBI_API_URL): 8 mocks cobrindo categorias B1-B7 e os 4 status.
// 3 deles (P1001, P1002, P1004) ficaram elegiveis para avaliacao em ABRIL/2026
// — instalacaoFinalizada=true e pedidoVistoriaDate dentro de marco/2026.
export const MOCK_PROJECTS: PbiProject[] = [
  {
    codigoProjeto: "P1001",
    clientName: "Joao Silva",
    address: "Rua das Flores, 123",
    city: "Belo Horizonte",
    state: "MG",
    powerKwp: 4.5,
    category: "B1",
    status: "completed",
    moduleCount: 9,
    startDate: "2026-03-08",
    endDate: "2026-03-10",
    vendedor: "Carlos Vieira",
    installacaoFinalizada: true,
    pedidoVistoriaDate: "2026-03-12",
  },
  {
    codigoProjeto: "P1002",
    clientName: "Maria Santos",
    address: "Av. Bias Fortes, 1500",
    city: "Contagem",
    state: "MG",
    powerKwp: 8.5,
    category: "B2",
    status: "completed",
    moduleCount: 16,
    startDate: "2026-03-15",
    endDate: "2026-03-18",
    vendedor: "Ana Cardoso",
    installacaoFinalizada: true,
    pedidoVistoriaDate: "2026-03-19",
  },
  {
    codigoProjeto: "P1003",
    clientName: "Tech Solar Ltda",
    address: "Rua Pernambuco, 350",
    city: "Belo Horizonte",
    state: "MG",
    powerKwp: 18,
    category: "B3",
    status: "in_progress",
    moduleCount: 36,
    startDate: "2026-04-22",
    endDate: null,
    vendedor: "Carlos Vieira",
    installacaoFinalizada: false,
    pedidoVistoriaDate: null,
  },
  {
    codigoProjeto: "P1004",
    clientName: "Construtora ABC",
    address: "Rod. BR-381, km 489",
    city: "Betim",
    state: "MG",
    powerKwp: 28,
    category: "B4",
    status: "completed",
    moduleCount: 56,
    startDate: "2026-03-25",
    endDate: "2026-03-29",
    vendedor: "Roberto Lima",
    installacaoFinalizada: true,
    pedidoVistoriaDate: "2026-03-30",
  },
  {
    codigoProjeto: "P1005",
    clientName: "Industria XYZ",
    address: "Av. das Industrias, 8000",
    city: "Nova Lima",
    state: "MG",
    powerKwp: 45,
    category: "B5",
    status: "in_progress",
    moduleCount: 90,
    startDate: "2026-04-10",
    endDate: null,
    vendedor: "Ana Cardoso",
    installacaoFinalizada: false,
    pedidoVistoriaDate: null,
  },
  {
    codigoProjeto: "P1006",
    clientName: "Hotel Estrela",
    address: "Praca Tiradentes, 50",
    city: "Ouro Preto",
    state: "MG",
    powerKwp: 65,
    category: "B6",
    status: "planning",
    moduleCount: 130,
    startDate: null,
    endDate: null,
    vendedor: "Roberto Lima",
    installacaoFinalizada: false,
    pedidoVistoriaDate: null,
  },
  {
    codigoProjeto: "P1007",
    clientName: "Hospital Sao Lucas",
    address: "R. Aimores, 1200",
    city: "Sete Lagoas",
    state: "MG",
    powerKwp: 95,
    category: "B7",
    // Concluido mas vistoria foi em FEVEREIRO — nao deve aparecer na janela de marco
    status: "completed",
    moduleCount: 190,
    startDate: "2026-02-18",
    endDate: "2026-02-25",
    vendedor: "Carlos Vieira",
    installacaoFinalizada: true,
    pedidoVistoriaDate: "2026-02-27",
  },
  {
    codigoProjeto: "P1008",
    clientName: "Padaria Pao Quente",
    address: "Av. Brasil, 88",
    city: "Itabira",
    state: "MG",
    powerKwp: 6.2,
    category: "B2",
    status: "cancelled",
    moduleCount: 12,
    startDate: "2026-01-30",
    endDate: null,
    vendedor: "Ana Cardoso",
    installacaoFinalizada: false,
    pedidoVistoriaDate: null,
  },
];
