// Projetos simulados — usados quando PBI_API_URL nao esta configurada.
// Cobrem todas as categorias (B1..B7) e os 4 status do schema.
// Remover quando integrar a API form-pbi de verdade.

import type { PbiProject } from "./pbiClient";

export const MOCK_PROJECTS: PbiProject[] = [
  {
    codigoProjeto: "P1001",
    clientName: "Joao Silva",
    address: "Rua das Flores, 123",
    city: "Belo Horizonte",
    state: "MG",
    powerKwp: 4.5,
    category: "B1",
    status: "completed",
    moduleCount: 9,
    startDate: "2025-12-10",
    endDate: "2025-12-12",
    vendedor: "Carlos Vieira",
  },
  {
    codigoProjeto: "P1002",
    clientName: "Maria Santos",
    address: "Av. Bias Fortes, 1500",
    city: "Contagem",
    state: "MG",
    powerKwp: 8.5,
    category: "B2",
    status: "completed",
    moduleCount: 16,
    startDate: "2026-01-15",
    endDate: "2026-01-18",
    vendedor: "Ana Cardoso",
  },
  {
    codigoProjeto: "P1003",
    clientName: "Tech Solar Ltda",
    address: "Rua Pernambuco, 350",
    city: "Belo Horizonte",
    state: "MG",
    powerKwp: 18,
    category: "B3",
    status: "in_progress",
    moduleCount: 36,
    startDate: "2026-04-22",
    endDate: null,
    vendedor: "Carlos Vieira",
  },
  {
    codigoProjeto: "P1004",
    clientName: "Construtora ABC",
    address: "Rod. BR-381, km 489",
    city: "Betim",
    state: "MG",
    powerKwp: 28,
    category: "B4",
    status: "completed",
    moduleCount: 56,
    startDate: "2026-02-05",
    endDate: "2026-02-15",
    vendedor: "Roberto Lima",
  },
  {
    codigoProjeto: "P1005",
    clientName: "Industria XYZ",
    address: "Av. das Industrias, 8000",
    city: "Nova Lima",
    state: "MG",
    powerKwp: 45,
    category: "B5",
    status: "in_progress",
    moduleCount: 90,
    startDate: "2026-04-10",
    endDate: null,
    vendedor: "Ana Cardoso",
  },
  {
    codigoProjeto: "P1006",
    clientName: "Hotel Estrela",
    address: "Praca Tiradentes, 50",
    city: "Ouro Preto",
    state: "MG",
    powerKwp: 65,
    category: "B6",
    status: "planning",
    moduleCount: 130,
    startDate: null,
    endDate: null,
    vendedor: "Roberto Lima",
  },
  {
    codigoProjeto: "P1007",
    clientName: "Hospital Sao Lucas",
    address: "R. Aimores, 1200",
    city: "Sete Lagoas",
    state: "MG",
    powerKwp: 95,
    category: "B7",
    status: "in_progress",
    moduleCount: 190,
    startDate: "2026-03-18",
    endDate: null,
    vendedor: "Carlos Vieira",
  },
  {
    codigoProjeto: "P1008",
    clientName: "Padaria Pao Quente",
    address: "Av. Brasil, 88",
    city: "Itabira",
    state: "MG",
    powerKwp: 6.2,
    category: "B2",
    status: "cancelled",
    moduleCount: 12,
    startDate: "2026-01-30",
    endDate: null,
    vendedor: "Ana Cardoso",
  },
];
